In [1]:
import pandas as pd
import numpy as np
from google_play_scraper import app
from google_play_scraper import Sort, reviews
from nltk.sem.chat80 import country

In [2]:
result, continuation_token = reviews(
    # https://play.google.com/store/apps/details?id=com.fatsecret.android
    'com.fatsecret.android',
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=10500,
    filter_score_with=None
)

In [3]:
df_scraped = pd.DataFrame(np.array(result), columns=['reviews'])
df_scraped = df_scraped.join(pd.DataFrame(df_scraped.pop('reviews').tolist()))
df_scraped.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,7970a839-391e-4a94-8a19-cec20ab05ef9,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,sangat membantu mengontrol makanan harian,5,0,None,2025-09-25 09:50:09,None,NaT,None
1,88338650-ea70-40e5-858c-3b0f4b6dd32a,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Sangat membantu...!,5,0,None,2025-09-25 06:01:24,None,NaT,None
2,ee2c030f-89ca-405f-b45c-33ae0feababd,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,sangat membantu,5,0,9.44.2.3,2025-09-20 06:00:53,None,NaT,9.44.2.3
3,17bbc5dd-555b-42c9-b4d8-cdc3cabfcfc1,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Terima kasih. sangat membantu,5,0,None,2025-09-19 05:57:22,None,NaT,None
4,bd36ab66-8960-4fb1-9de5-96ba832c28ea,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"sangatlah baguss, saya bis akonsisten memakai ini",5,0,10.1.0.7,2025-09-18 20:45:47,None,NaT,10.1.0.7

In [4]:
len(df_scraped.index)

8240

In [5]:
df_scraped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8240 entries, 0 to 8239
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              8240 non-null   object
 1   userName              8240 non-null   object
 2   userImage             8240 non-null   object
 3   content               8240 non-null   object
 4   score                 8240 non-null   int64
 5   thumbsUpCount         8240 non-null   int64
 6   reviewCreatedVersion  6981 non-null   object
 7   at                    8240 non-null   datetime64[ns]
 8   replyContent          211 non-null    object
 9   repliedAt             211 non-null    datetime64[ns]
 10  appVersion            6981 non-null   object
dtypes: datetime64[ns](2), int64(2), object(7)
memory usage: 708.3+ KB

In [6]:
df_scraped[['userName', 'score', 'at', 'content']].head()

,userName,score,at,content
0,Pengguna Google,5,2025-09-25 09:50:09,sangat membantu mengontrol makanan harian
1,Pengguna Google,5,2025-09-25 06:01:24,Sangat membantu...!
2,Pengguna Google,5,2025-09-20 06:00:53,sangat membantu
3,Pengguna Google,5,2025-09-19 05:57:22,Terima kasih. sangat membantu
4,Pengguna Google,5,2025-09-18 20:45:47,"sangatlah baguss, saya bis akonsisten memakai ini"

In [9]:
my_df = df_scraped[['userName', 'score', 'at', 'content']]
my_df.to_csv('fatsecret_scraped.csv', index=False)